In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
array=np.array([1,2,3,4,5,6,7])

In [7]:
array

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
array.ndim

1

In [11]:
array.dtype

dtype('int32')

In [13]:
array.shape

(7,)

In [17]:
np.zeros(10)        #create array of only zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
x=np.ones(5)          #create array of only ones

In [25]:
x.dtype

dtype('float64')

In [27]:
np.eye(4)   #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.arange(1,10,2)  #gap of 2

array([1, 3, 5, 7, 9])

In [35]:
np.linspace(1,20,5)     

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [37]:
array=np.array([7,23,42,1,2])

In [39]:
array[0]

7

In [41]:
array[1]

23

In [43]:
array[-1]

2

In [45]:
array[1:3]

array([23, 42])

In [47]:
array[2]=99

In [50]:
array

array([ 7, 23, 99,  1,  2])

In [54]:
array1=np.array([[1,2,3],[6,7,8]])

In [56]:
array1

array([[1, 2, 3],
       [6, 7, 8]])

In [58]:
array1.shape

(2, 3)

In [60]:
array1.ndim

2

In [62]:
array1.reshape(3,2)

array([[1, 2],
       [3, 6],
       [7, 8]])

In [64]:
a=np.array([[1,2,3],[4,5,6]])

In [66]:
b=np.array([[1,2,3],[4,5,6]])

In [68]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [70]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [72]:
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [77]:
a[0][2]

3

In [79]:
a[0,2]

3

In [87]:
np.random.randint(10)

7

In [91]:
np.random.randint(1,10,(3,3))

array([[2, 6, 1],
       [3, 5, 9],
       [5, 1, 9]])

In [95]:
np.random.randn(1,10)

array([[-2.1827995 , -1.27179741, -1.18913362,  0.70647963, -1.90069321,
         0.33715128, -1.72960432, -0.66551105, -0.34291166, -0.96527069]])

In [97]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.mean(a)

3.5

In [101]:
np.median(a)

3.5

In [103]:
np.std(a)

1.707825127659933

In [105]:
np.max(a)

6

In [107]:
np.min(a)

1

In [109]:
np.sum(a)

21