In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])  #array creation

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.ndim  #dimention

1

In [6]:
arr.dtype #datatype

dtype('int32')

In [8]:
arr.shape  #return rows and columns

(6,)

In [9]:
np.zeros(10)  

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
x = np.ones(5)

In [12]:
x.dtype

dtype('float64')

In [13]:
np.eye(4)  #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.arange(1,10,2)  #starting, ending, skip elements

array([1, 3, 5, 7, 9])

In [19]:
np.linspace(1,100,20) #it gives same difference between all elements

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [20]:
arr = np.array([7,23,45,1,2])

In [21]:
arr[0] #indexing supports

7

In [22]:
arr[1]

23

In [23]:
arr[-1]

2

In [26]:
arr[1:3]  #slicing supports

array([23, 45])

In [27]:
arr[1]= 10  #can update the value also

In [28]:
arr

array([ 7, 10, 45,  1,  2])

In [30]:
arr = np.array([[1,2,3],[4,5,6]])  #2D array

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr.shape

(2, 3)

In [33]:
arr.ndim

2

In [34]:
arr.reshape(3,2)  #reshape the 2d array, value exists in the existing 2d array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
a = np.array([[1,2,3],[4,5,6]])

In [37]:
b = np.array([[1,2,3],[4,5,6]])

In [38]:
a + b  #index wise operations

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [39]:
a*b # division and subtraction also done by this

array([[ 1,  4,  9],
       [16, 25, 36]])

In [40]:
a[0][1]  #find elements by their index [row][column]

2

In [41]:
a[0,2] #another way to find

3

In [44]:
np.random.randint(10)  #it gives random integer number

9

In [45]:
np.random.randint(1,100,(3,3))  #creating random array by randon function

array([[34, 10, 60],
       [23,  1, 58],
       [72, 91, 80]])

In [46]:
np.random.randn(1,10)  #normal distribution

array([[-1.13469335,  1.2880291 , -0.35266892, -1.35555414,  2.35256717,
        -0.77373807, -1.85368815, -0.09133705,  0.61638562, -0.20879993]])

In [47]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.mean(a)

3.5

In [49]:
np.median(a)

3.5

In [51]:
np.std(a)

1.707825127659933

In [52]:
#TASK:  STandard deviation, normal distribution

In [53]:
np.min(a)

1

In [54]:
np.max(a)

6

In [55]:
np.sum(a)

21